<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PhotonVoice</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Il2CppDummyDll">
      <HintPath>../../dumps/il2cpp/DummyDll/Il2CppDummyDll.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>../../dumps/il2cpp/DummyDll/PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.API">
      <HintPath>../../dumps/il2cpp/DummyDll/PhotonVoice.API.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>../../dumps/il2cpp/DummyDll/Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>