<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Il2CppDummyDll">
      <HintPath>../../dumps/il2cpp/DummyDll/Il2CppDummyDll.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Security">
      <HintPath>../../dumps/il2cpp/DummyDll/Mono.Security.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration">
      <HintPath>../../dumps/il2cpp/DummyDll/System.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../dumps/il2cpp/DummyDll/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Data">
      <HintPath>../../dumps/il2cpp/DummyDll/System.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Private.CoreLib" />
  </ItemGroup>
</Project>