<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Scripts</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Il2CppDummyDll">
      <HintPath>../../../dumps/il2cpp/DummyDll/Il2CppDummyDll.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>../../../dumps/il2cpp/DummyDll/PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../dumps/il2cpp/DummyDll/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Gisketch.Aottg2UI.Runtime">
      <HintPath>../../../dumps/il2cpp/DummyDll/Gisketch.Aottg2UI.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>../../../dumps/il2cpp/DummyDll/PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>../../../dumps/il2cpp/DummyDll/Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="StandardAssets.Effects">
      <HintPath>../../../dumps/il2cpp/DummyDll/StandardAssets.Effects.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>../../../dumps/il2cpp/DummyDll/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>../../../dumps/il2cpp/DummyDll/DOTween.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.PUN">
      <HintPath>../../../dumps/il2cpp/DummyDll/PhotonVoice.PUN.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice">
      <HintPath>../../../dumps/il2cpp/DummyDll/PhotonVoice.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>../../../dumps/il2cpp/DummyDll/Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>../../../dumps/il2cpp/DummyDll/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../dumps/il2cpp/DummyDll/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>../../../dumps/il2cpp/DummyDll/Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking.Utilities">
      <HintPath>../../../dumps/il2cpp/DummyDll/PhotonUnityNetworking.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>../../../dumps/il2cpp/DummyDll/UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="Discord">
      <HintPath>../../../dumps/il2cpp/DummyDll/Discord.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>../../../dumps/il2cpp/DummyDll/UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>