<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Gisketch.Aottg2UI.Runtime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Il2CppDummyDll">
      <HintPath>../../dumps/il2cpp/DummyDll/Il2CppDummyDll.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../dumps/il2cpp/DummyDll/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>../../dumps/il2cpp/DummyDll/DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>../../dumps/il2cpp/DummyDll/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Gilzoide.FlexUi">
      <HintPath>../../dumps/il2cpp/DummyDll/Gilzoide.FlexUi.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>../../dumps/il2cpp/DummyDll/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>