using System.Collections;
using System.ComponentModel;
using Il2CppDummyDll;

namespace System.Data;

[Token(Token = "0x2000009")]
[DefaultEvent("CollectionChanged")]
public sealed class ConstraintCollection : InternalDataCollectionBase
{
	[Token(Token = "0x4000018")]
	[FieldOffset(Offset = "0x10")]
	private readonly DataTable _table;

	[Token(Token = "0x4000019")]
	[FieldOffset(Offset = "0x18")]
	private readonly ArrayList _list;

	[Token(Token = "0x400001A")]
	[FieldOffset(Offset = "0x20")]
	private int _defaultNameIndex;

	[Token(Token = "0x400001B")]
	[FieldOffset(Offset = "0x28")]
	private CollectionChangeEventHandler _onCollectionChanged;

	[Token(Token = "0x400001C")]
	[FieldOffset(Offset = "0x30")]
	private Constraint[] _delayLoadingConstraints;

	[Token(Token = "0x400001D")]
	[FieldOffset(Offset = "0x38")]
	private bool _fLoadForeignKeyConstraintsOnly;

	[Token(Token = "0x1700000B")]
	protected override ArrayList List
	{
		[Token(Token = "0x600003D")]
		[Address(RVA = "0x41F6750", Offset = "0x41F6750", VA = "0x41F6750", Slot = "12")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x1700000C")]
	public Constraint this[int index]
	{
		[Token(Token = "0x600003E")]
		[Address(RVA = "0x41F6760", Offset = "0x41F6760", VA = "0x41F6760")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x1700000D")]
	internal DataTable Table
	{
		[Token(Token = "0x600003F")]
		[Address(RVA = "0x41F6960", Offset = "0x41F6960", VA = "0x41F6960")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x1700000E")]
	public Constraint this[string name]
	{
		[Token(Token = "0x6000040")]
		[Address(RVA = "0x41F6970", Offset = "0x41F6970", VA = "0x41F6970")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x600003C")]
	[Address(RVA = "0x41F66A0", Offset = "0x41F66A0", VA = "0x41F66A0")]
	internal ConstraintCollection(DataTable table)
	{
	}

	[Token(Token = "0x6000041")]
	[Address(RVA = "0x41F6D50", Offset = "0x41F6D50", VA = "0x41F6D50")]
	public void Add(Constraint constraint)
	{
	}

	[Token(Token = "0x6000042")]
	[Address(RVA = "0x41F6D60", Offset = "0x41F6D60", VA = "0x41F6D60")]
	internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
	{
	}

	[Token(Token = "0x6000043")]
	[Address(RVA = "0x41F7BF0", Offset = "0x41F7BF0", VA = "0x41F7BF0")]
	public Constraint Add(string name, DataColumn[] columns, bool primaryKey)
	{
		return null;
	}

	[Token(Token = "0x6000044")]
	[Address(RVA = "0x41F77A0", Offset = "0x41F77A0", VA = "0x41F77A0")]
	private void AddUniqueConstraint(UniqueConstraint constraint)
	{
	}

	[Token(Token = "0x6000045")]
	[Address(RVA = "0x41F7A50", Offset = "0x41F7A50", VA = "0x41F7A50")]
	private void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
	{
	}

	[Token(Token = "0x6000046")]
	[Address(RVA = "0x41F7560", Offset = "0x41F7560", VA = "0x41F7560")]
	private bool AutoGenerated(Constraint constraint)
	{
		return default(bool);
	}

	[Token(Token = "0x6000047")]
	[Address(RVA = "0x41F7B90", Offset = "0x41F7B90", VA = "0x41F7B90")]
	private void ArrayAdd(Constraint constraint)
	{
	}

	[Token(Token = "0x6000048")]
	[Address(RVA = "0x41F7E00", Offset = "0x41F7E00", VA = "0x41F7E00")]
	private void ArrayRemove(Constraint constraint)
	{
	}

	[Token(Token = "0x6000049")]
	[Address(RVA = "0x41F7A30", Offset = "0x41F7A30", VA = "0x41F7A30")]
	internal string AssignName()
	{
		return null;
	}

	[Token(Token = "0x600004A")]
	[Address(RVA = "0x41F7AC0", Offset = "0x41F7AC0", VA = "0x41F7AC0")]
	private void BaseAdd(Constraint constraint)
	{
	}

	[Token(Token = "0x600004B")]
	[Address(RVA = "0x41F7EF0", Offset = "0x41F7EF0", VA = "0x41F7EF0")]
	private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength)
	{
	}

	[Token(Token = "0x600004C")]
	[Address(RVA = "0x41F80D0", Offset = "0x41F80D0", VA = "0x41F80D0")]
	private void BaseRemove(Constraint constraint)
	{
	}

	[Token(Token = "0x600004D")]
	[Address(RVA = "0x41F8470", Offset = "0x41F8470", VA = "0x41F8470")]
	internal bool CanRemove(Constraint constraint, bool fThrowException)
	{
		return default(bool);
	}

	[Token(Token = "0x600004E")]
	[Address(RVA = "0x41F84A0", Offset = "0x41F84A0", VA = "0x41F84A0")]
	public void Clear()
	{
	}

	[Token(Token = "0x600004F")]
	[Address(RVA = "0x41F8930", Offset = "0x41F8930", VA = "0x41F8930")]
	public bool Contains(string name)
	{
		return default(bool);
	}

	[Token(Token = "0x6000050")]
	[Address(RVA = "0x41F8940", Offset = "0x41F8940", VA = "0x41F8940")]
	internal bool Contains(string name, bool caseSensitive)
	{
		return default(bool);
	}

	[Token(Token = "0x6000051")]
	[Address(RVA = "0x41F7290", Offset = "0x41F7290", VA = "0x41F7290")]
	internal Constraint FindConstraint(Constraint constraint)
	{
		return null;
	}

	[Token(Token = "0x6000052")]
	[Address(RVA = "0x41F7860", Offset = "0x41F7860", VA = "0x41F7860")]
	internal UniqueConstraint FindKeyConstraint(DataColumn[] columns)
	{
		return null;
	}

	[Token(Token = "0x6000053")]
	[Address(RVA = "0x41F8AD0", Offset = "0x41F8AD0", VA = "0x41F8AD0")]
	internal UniqueConstraint FindKeyConstraint(DataColumn column)
	{
		return null;
	}

	[Token(Token = "0x6000054")]
	[Address(RVA = "0x41F8BE0", Offset = "0x41F8BE0", VA = "0x41F8BE0")]
	internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns)
	{
		return null;
	}

	[Token(Token = "0x6000055")]
	[Address(RVA = "0x41F8A60", Offset = "0x41F8A60", VA = "0x41F8A60")]
	private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2)
	{
		return default(bool);
	}

	[Token(Token = "0x6000056")]
	[Address(RVA = "0x41F6A50", Offset = "0x41F6A50", VA = "0x41F6A50")]
	internal int InternalIndexOf(string constraintName)
	{
		return default(int);
	}

	[Token(Token = "0x6000057")]
	[Address(RVA = "0x41F7E40", Offset = "0x41F7E40", VA = "0x41F7E40")]
	private string MakeName(int index)
	{
		return null;
	}

	[Token(Token = "0x6000058")]
	[Address(RVA = "0x41F7BD0", Offset = "0x41F7BD0", VA = "0x41F7BD0")]
	private void OnCollectionChanged(CollectionChangeEventArgs ccevent)
	{
	}

	[Token(Token = "0x6000059")]
	[Address(RVA = "0x41F5E90", Offset = "0x41F5E90", VA = "0x41F5E90")]
	internal void RegisterName(string name)
	{
	}

	[Token(Token = "0x600005A")]
	[Address(RVA = "0x41F8F60", Offset = "0x41F8F60", VA = "0x41F8F60")]
	public void Remove(Constraint constraint)
	{
	}

	[Token(Token = "0x600005B")]
	[Address(RVA = "0x41F60C0", Offset = "0x41F60C0", VA = "0x41F60C0")]
	internal void UnregisterName(string name)
	{
	}

	[Token(Token = "0x600005C")]
	[Address(RVA = "0x41F90D0", Offset = "0x41F90D0", VA = "0x41F90D0")]
	internal void FinishInitConstraints()
	{
	}
}
