// ==================== AoTTG2 cross-reference ====================
// Type: System.Data.ConstraintCollection
// Update status: unchanged since the previous dump
// No native C: this type has no methods, or its assembly is out of native scope.
// Prior real C# source: none (type is newer than the last public source snapshot)
// Bodies below are empty IL2CPP metadata stubs; the logic lives in the native C.
// ===============================================================
using System.Collections;
using System.ComponentModel;
using Il2CppDummyDll;

namespace System.Data;

[Token(Token = "0x2000009")]
[DefaultEvent("CollectionChanged")]
public sealed class ConstraintCollection : InternalDataCollectionBase
{
	[Token(Token = "0x4000018")]
	[FieldOffset(Offset = "0x10")]
	private readonly DataTable _table;

	[Token(Token = "0x4000019")]
	[FieldOffset(Offset = "0x18")]
	private readonly ArrayList _list;

	[Token(Token = "0x400001A")]
	[FieldOffset(Offset = "0x20")]
	private int _defaultNameIndex;

	[Token(Token = "0x400001B")]
	[FieldOffset(Offset = "0x28")]
	private CollectionChangeEventHandler _onCollectionChanged;

	[Token(Token = "0x400001C")]
	[FieldOffset(Offset = "0x30")]
	private Constraint[] _delayLoadingConstraints;

	[Token(Token = "0x400001D")]
	[FieldOffset(Offset = "0x38")]
	private bool _fLoadForeignKeyConstraintsOnly;

	[Token(Token = "0x1700000B")]
	protected override ArrayList List
	{
		[Token(Token = "0x600003D")]
		[Address(RVA = "0x4533EB0", Offset = "0x4533EB0", VA = "0x4533EB0", Slot = "12")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x1700000C")]
	public Constraint this[int index]
	{
		[Token(Token = "0x600003E")]
		[Address(RVA = "0x4533EC0", Offset = "0x4533EC0", VA = "0x4533EC0")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x1700000D")]
	internal DataTable Table
	{
		[Token(Token = "0x600003F")]
		[Address(RVA = "0x45340C0", Offset = "0x45340C0", VA = "0x45340C0")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x1700000E")]
	public Constraint this[string name]
	{
		[Token(Token = "0x6000040")]
		[Address(RVA = "0x45340D0", Offset = "0x45340D0", VA = "0x45340D0")]
		get
		{
			return null;
		}
	}

	[Token(Token = "0x600003C")]
	[Address(RVA = "0x4533E00", Offset = "0x4533E00", VA = "0x4533E00")]
	internal ConstraintCollection(DataTable table)
	{
	}

	[Token(Token = "0x6000041")]
	[Address(RVA = "0x45344B0", Offset = "0x45344B0", VA = "0x45344B0")]
	public void Add(Constraint constraint)
	{
	}

	[Token(Token = "0x6000042")]
	[Address(RVA = "0x45344C0", Offset = "0x45344C0", VA = "0x45344C0")]
	internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
	{
	}

	[Token(Token = "0x6000043")]
	[Address(RVA = "0x4535350", Offset = "0x4535350", VA = "0x4535350")]
	public Constraint Add(string name, DataColumn[] columns, bool primaryKey)
	{
		return null;
	}

	[Token(Token = "0x6000044")]
	[Address(RVA = "0x4534F00", Offset = "0x4534F00", VA = "0x4534F00")]
	private void AddUniqueConstraint(UniqueConstraint constraint)
	{
	}

	[Token(Token = "0x6000045")]
	[Address(RVA = "0x45351B0", Offset = "0x45351B0", VA = "0x45351B0")]
	private void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
	{
	}

	[Token(Token = "0x6000046")]
	[Address(RVA = "0x4534CC0", Offset = "0x4534CC0", VA = "0x4534CC0")]
	private bool AutoGenerated(Constraint constraint)
	{
		return default(bool);
	}

	[Token(Token = "0x6000047")]
	[Address(RVA = "0x45352F0", Offset = "0x45352F0", VA = "0x45352F0")]
	private void ArrayAdd(Constraint constraint)
	{
	}

	[Token(Token = "0x6000048")]
	[Address(RVA = "0x4535560", Offset = "0x4535560", VA = "0x4535560")]
	private void ArrayRemove(Constraint constraint)
	{
	}

	[Token(Token = "0x6000049")]
	[Address(RVA = "0x4535190", Offset = "0x4535190", VA = "0x4535190")]
	internal string AssignName()
	{
		return null;
	}

	[Token(Token = "0x600004A")]
	[Address(RVA = "0x4535220", Offset = "0x4535220", VA = "0x4535220")]
	private void BaseAdd(Constraint constraint)
	{
	}

	[Token(Token = "0x600004B")]
	[Address(RVA = "0x4535650", Offset = "0x4535650", VA = "0x4535650")]
	private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength)
	{
	}

	[Token(Token = "0x600004C")]
	[Address(RVA = "0x4535830", Offset = "0x4535830", VA = "0x4535830")]
	private void BaseRemove(Constraint constraint)
	{
	}

	[Token(Token = "0x600004D")]
	[Address(RVA = "0x4535BD0", Offset = "0x4535BD0", VA = "0x4535BD0")]
	internal bool CanRemove(Constraint constraint, bool fThrowException)
	{
		return default(bool);
	}

	[Token(Token = "0x600004E")]
	[Address(RVA = "0x4535C00", Offset = "0x4535C00", VA = "0x4535C00")]
	public void Clear()
	{
	}

	[Token(Token = "0x600004F")]
	[Address(RVA = "0x4536090", Offset = "0x4536090", VA = "0x4536090")]
	public bool Contains(string name)
	{
		return default(bool);
	}

	[Token(Token = "0x6000050")]
	[Address(RVA = "0x45360A0", Offset = "0x45360A0", VA = "0x45360A0")]
	internal bool Contains(string name, bool caseSensitive)
	{
		return default(bool);
	}

	[Token(Token = "0x6000051")]
	[Address(RVA = "0x45349F0", Offset = "0x45349F0", VA = "0x45349F0")]
	internal Constraint FindConstraint(Constraint constraint)
	{
		return null;
	}

	[Token(Token = "0x6000052")]
	[Address(RVA = "0x4534FC0", Offset = "0x4534FC0", VA = "0x4534FC0")]
	internal UniqueConstraint FindKeyConstraint(DataColumn[] columns)
	{
		return null;
	}

	[Token(Token = "0x6000053")]
	[Address(RVA = "0x4536230", Offset = "0x4536230", VA = "0x4536230")]
	internal UniqueConstraint FindKeyConstraint(DataColumn column)
	{
		return null;
	}

	[Token(Token = "0x6000054")]
	[Address(RVA = "0x4536340", Offset = "0x4536340", VA = "0x4536340")]
	internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns)
	{
		return null;
	}

	[Token(Token = "0x6000055")]
	[Address(RVA = "0x45361C0", Offset = "0x45361C0", VA = "0x45361C0")]
	private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2)
	{
		return default(bool);
	}

	[Token(Token = "0x6000056")]
	[Address(RVA = "0x45341B0", Offset = "0x45341B0", VA = "0x45341B0")]
	internal int InternalIndexOf(string constraintName)
	{
		return default(int);
	}

	[Token(Token = "0x6000057")]
	[Address(RVA = "0x45355A0", Offset = "0x45355A0", VA = "0x45355A0")]
	private string MakeName(int index)
	{
		return null;
	}

	[Token(Token = "0x6000058")]
	[Address(RVA = "0x4535330", Offset = "0x4535330", VA = "0x4535330")]
	private void OnCollectionChanged(CollectionChangeEventArgs ccevent)
	{
	}

	[Token(Token = "0x6000059")]
	[Address(RVA = "0x45335F0", Offset = "0x45335F0", VA = "0x45335F0")]
	internal void RegisterName(string name)
	{
	}

	[Token(Token = "0x600005A")]
	[Address(RVA = "0x45366C0", Offset = "0x45366C0", VA = "0x45366C0")]
	public void Remove(Constraint constraint)
	{
	}

	[Token(Token = "0x600005B")]
	[Address(RVA = "0x4533820", Offset = "0x4533820", VA = "0x4533820")]
	internal void UnregisterName(string name)
	{
	}

	[Token(Token = "0x600005C")]
	[Address(RVA = "0x4536830", Offset = "0x4536830", VA = "0x4536830")]
	internal void FinishInitConstraints()
	{
	}
}
