using System.Collections;
using System.ComponentModel;
using System.Xml;
using Il2CppDummyDll;

namespace System.Data;

[Token(Token = "0x2000098")]
internal sealed class XmlTreeGen
{
	[Token(Token = "0x4000321")]
	[FieldOffset(Offset = "0x10")]
	private ArrayList _constraintNames;

	[Token(Token = "0x4000322")]
	[FieldOffset(Offset = "0x18")]
	private Hashtable _namespaces;

	[Token(Token = "0x4000323")]
	[FieldOffset(Offset = "0x20")]
	private Hashtable _autogenerated;

	[Token(Token = "0x4000324")]
	[FieldOffset(Offset = "0x28")]
	private Hashtable _prefixes;

	[Token(Token = "0x4000325")]
	[FieldOffset(Offset = "0x30")]
	private DataSet _ds;

	[Token(Token = "0x4000326")]
	[FieldOffset(Offset = "0x38")]
	private ArrayList _tables;

	[Token(Token = "0x4000327")]
	[FieldOffset(Offset = "0x40")]
	private ArrayList _relations;

	[Token(Token = "0x4000328")]
	[FieldOffset(Offset = "0x48")]
	private XmlDocument _dc;

	[Token(Token = "0x4000329")]
	[FieldOffset(Offset = "0x50")]
	private XmlElement _sRoot;

	[Token(Token = "0x400032A")]
	[FieldOffset(Offset = "0x58")]
	private int _prefixCount;

	[Token(Token = "0x400032B")]
	[FieldOffset(Offset = "0x5C")]
	private SchemaFormat _schFormat;

	[Token(Token = "0x400032C")]
	[FieldOffset(Offset = "0x60")]
	private string _filePath;

	[Token(Token = "0x400032D")]
	[FieldOffset(Offset = "0x68")]
	private string _fileName;

	[Token(Token = "0x400032E")]
	[FieldOffset(Offset = "0x70")]
	private string _fileExt;

	[Token(Token = "0x400032F")]
	[FieldOffset(Offset = "0x78")]
	private XmlElement _dsElement;

	[Token(Token = "0x4000330")]
	[FieldOffset(Offset = "0x80")]
	private XmlElement _constraintSeparator;

	[Token(Token = "0x4000331")]
	[FieldOffset(Offset = "0x88")]
	private Converter<Type, string> _targetConverter;

	[Token(Token = "0x600086A")]
	[Address(RVA = "0x42AD260", Offset = "0x42AD260", VA = "0x42AD260")]
	internal XmlTreeGen(SchemaFormat format)
	{
	}

	[Token(Token = "0x600086B")]
	[Address(RVA = "0x42AD300", Offset = "0x42AD300", VA = "0x42AD300")]
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node)
	{
	}

	[Token(Token = "0x600086C")]
	[Address(RVA = "0x42AD310", Offset = "0x42AD310", VA = "0x42AD310")]
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node, Type type)
	{
	}

	[Token(Token = "0x600086D")]
	[Address(RVA = "0x42ADAB0", Offset = "0x42ADAB0", VA = "0x42ADAB0")]
	internal void AddXdoProperties(object instance, XmlElement root, XmlDocument xd)
	{
	}

	[Token(Token = "0x600086E")]
	[Address(RVA = "0x42ADC30", Offset = "0x42ADC30", VA = "0x42ADC30")]
	internal void AddXdoProperty(PropertyDescriptor pd, object instance, XmlElement root, XmlDocument xd)
	{
	}

	[Token(Token = "0x600086F")]
	[Address(RVA = "0x42AE5E0", Offset = "0x42AE5E0", VA = "0x42AE5E0")]
	internal static string XmlDataTypeName(Type type)
	{
		return null;
	}

	[Token(Token = "0x6000870")]
	[Address(RVA = "0x42AF3D0", Offset = "0x42AF3D0", VA = "0x42AF3D0")]
	private void GenerateConstraintNames(DataTable table, bool fromTable)
	{
	}

	[Token(Token = "0x6000871")]
	[Address(RVA = "0x42AFAB0", Offset = "0x42AFAB0", VA = "0x42AFAB0")]
	private void GenerateConstraintNames(ArrayList tables)
	{
	}

	[Token(Token = "0x6000872")]
	[Address(RVA = "0x42AFB90", Offset = "0x42AFB90", VA = "0x42AFB90")]
	private void GenerateConstraintNames(DataSet ds)
	{
	}

	[Token(Token = "0x6000873")]
	[Address(RVA = "0x42AFEE0", Offset = "0x42AFEE0", VA = "0x42AFEE0")]
	private static bool _PropsNotEmpty(PropertyCollection props)
	{
		return default(bool);
	}

	[Token(Token = "0x6000874")]
	[Address(RVA = "0x42AFF10", Offset = "0x42AFF10", VA = "0x42AFF10")]
	private bool HaveExtendedProperties(DataSet ds)
	{
		return default(bool);
	}

	[Token(Token = "0x6000875")]
	[Address(RVA = "0x42B00E0", Offset = "0x42B00E0", VA = "0x42B00E0")]
	internal void WriteSchemaRoot(XmlDocument xd, XmlElement rootSchema, string targetNamespace)
	{
	}

	[Token(Token = "0x6000876")]
	[Address(RVA = "0x42B0310", Offset = "0x42B0310", VA = "0x42B0310")]
	internal static void ValidateColumnMapping(Type columnType)
	{
	}

	[Token(Token = "0x6000877")]
	[Address(RVA = "0x42B0380", Offset = "0x42B0380", VA = "0x42B0380")]
	internal void SetupAutoGenerated(DataSet ds)
	{
	}

	[Token(Token = "0x6000878")]
	[Address(RVA = "0x42B14D0", Offset = "0x42B14D0", VA = "0x42B14D0")]
	internal void SetupAutoGenerated(ArrayList dt)
	{
	}

	[Token(Token = "0x6000879")]
	[Address(RVA = "0x42B06D0", Offset = "0x42B06D0", VA = "0x42B06D0")]
	internal void SetupAutoGenerated(DataTable dt)
	{
	}

	[Token(Token = "0x600087A")]
	[Address(RVA = "0x42B1D10", Offset = "0x42B1D10", VA = "0x42B1D10")]
	private void CreateTablesHierarchy(DataTable dt)
	{
	}

	[Token(Token = "0x600087B")]
	[Address(RVA = "0x42B2150", Offset = "0x42B2150", VA = "0x42B2150")]
	private void CreateRelations(DataTable dt)
	{
	}

	[Token(Token = "0x600087C")]
	[Address(RVA = "0x42B2570", Offset = "0x42B2570", VA = "0x42B2570")]
	private DataTable[] CreateToplevelTables()
	{
		return null;
	}

	[Token(Token = "0x600087D")]
	[Address(RVA = "0x42B28D0", Offset = "0x42B28D0", VA = "0x42B28D0")]
	internal void SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy)
	{
	}

	[Token(Token = "0x600087E")]
	[Address(RVA = "0x42B6B10", Offset = "0x42B6B10", VA = "0x42B6B10")]
	internal XmlElement SchemaTree(XmlDocument xd, DataTable dt)
	{
		return null;
	}

	[Token(Token = "0x600087F")]
	[Address(RVA = "0x42B5D10", Offset = "0x42B5D10", VA = "0x42B5D10")]
	internal XmlElement FillDataSetElement(XmlDocument xd, DataSet ds, DataTable dt)
	{
		return null;
	}

	[Token(Token = "0x6000880")]
	[Address(RVA = "0x42B9E70", Offset = "0x42B9E70", VA = "0x42B9E70")]
	internal void SetPath(XmlWriter xw)
	{
	}

	[Token(Token = "0x6000881")]
	[Address(RVA = "0x42BA160", Offset = "0x42BA160", VA = "0x42BA160")]
	internal void Save(DataSet ds, XmlWriter xw)
	{
	}

	[Token(Token = "0x6000882")]
	[Address(RVA = "0x42BA190", Offset = "0x42BA190", VA = "0x42BA190")]
	internal void Save(DataTable dt, XmlWriter xw)
	{
	}

	[Token(Token = "0x6000883")]
	[Address(RVA = "0x42BA180", Offset = "0x42BA180", VA = "0x42BA180")]
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw)
	{
	}

	[Token(Token = "0x6000884")]
	[Address(RVA = "0x42BA240", Offset = "0x42BA240", VA = "0x42BA240")]
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy)
	{
	}

	[Token(Token = "0x6000885")]
	[Address(RVA = "0x42BA250", Offset = "0x42BA250", VA = "0x42BA250")]
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy, Converter<Type, string> multipleTargetConverter)
	{
	}

	[Token(Token = "0x6000886")]
	[Address(RVA = "0x42B6510", Offset = "0x42B6510", VA = "0x42B6510")]
	internal XmlElement HandleRelation(DataRelation rel, XmlDocument dc)
	{
		return null;
	}

	[Token(Token = "0x6000887")]
	[Address(RVA = "0x42BA390", Offset = "0x42BA390", VA = "0x42BA390")]
	private static XmlElement FindSimpleType(XmlElement schema, string name)
	{
		return null;
	}

	[Token(Token = "0x6000888")]
	[Address(RVA = "0x42BA490", Offset = "0x42BA490", VA = "0x42BA490")]
	internal XmlElement GetSchema(string NamespaceURI)
	{
		return null;
	}

	[Token(Token = "0x6000889")]
	[Address(RVA = "0x42BA700", Offset = "0x42BA700", VA = "0x42BA700")]
	internal void HandleColumnType(DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema)
	{
	}

	[Token(Token = "0x600088A")]
	[Address(RVA = "0x42BAC10", Offset = "0x42BAC10", VA = "0x42BAC10")]
	internal void AddColumnProperties(DataColumn col, XmlElement root)
	{
	}

	[Token(Token = "0x600088B")]
	[Address(RVA = "0x42BB260", Offset = "0x42BB260", VA = "0x42BB260")]
	private string FindTargetNamespace(DataTable table)
	{
		return null;
	}

	[Token(Token = "0x600088C")]
	[Address(RVA = "0x42BB380", Offset = "0x42BB380", VA = "0x42BB380")]
	internal XmlElement HandleColumn(DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal)
	{
		return null;
	}

	[Token(Token = "0x600088D")]
	[Address(RVA = "0x42BC130", Offset = "0x42BC130", VA = "0x42BC130")]
	internal static string TranslateAcceptRejectRule(AcceptRejectRule rule)
	{
		return null;
	}

	[Token(Token = "0x600088E")]
	[Address(RVA = "0x42BC180", Offset = "0x42BC180", VA = "0x42BC180")]
	internal static string TranslateRule(Rule rule)
	{
		return null;
	}

	[Token(Token = "0x600088F")]
	[Address(RVA = "0x42B6470", Offset = "0x42B6470", VA = "0x42B6470")]
	internal void AppendChildWithoutRef(XmlElement node, string Namespace, XmlElement el, string refString)
	{
	}

	[Token(Token = "0x6000890")]
	[Address(RVA = "0x42BBF60", Offset = "0x42BBF60", VA = "0x42BBF60")]
	internal XmlElement FindTypeNode(XmlElement node, string strType)
	{
		return null;
	}

	[Token(Token = "0x6000891")]
	[Address(RVA = "0x42B6460", Offset = "0x42B6460", VA = "0x42B6460")]
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema)
	{
		return null;
	}

	[Token(Token = "0x6000892")]
	[Address(RVA = "0x42BC210", Offset = "0x42BC210", VA = "0x42BC210")]
	private bool HasMixedColumns(DataTable table)
	{
		return default(bool);
	}

	[Token(Token = "0x6000893")]
	[Address(RVA = "0x42B15B0", Offset = "0x42B15B0", VA = "0x42B15B0")]
	internal static bool AutoGenerated(DataColumn col)
	{
		return default(bool);
	}

	[Token(Token = "0x6000894")]
	[Address(RVA = "0x42BC660", Offset = "0x42BC660", VA = "0x42BC660")]
	internal static bool AutoGenerated(DataRelation rel)
	{
		return default(bool);
	}

	[Token(Token = "0x6000895")]
	[Address(RVA = "0x42B1C50", Offset = "0x42B1C50", VA = "0x42B1C50")]
	internal static bool AutoGenerated(UniqueConstraint unique)
	{
		return default(bool);
	}

	[Token(Token = "0x6000896")]
	[Address(RVA = "0x42B1C40", Offset = "0x42B1C40", VA = "0x42B1C40")]
	private bool AutoGenerated(ForeignKeyConstraint fk)
	{
		return default(bool);
	}

	[Token(Token = "0x6000897")]
	[Address(RVA = "0x42BC760", Offset = "0x42BC760", VA = "0x42BC760")]
	internal static bool AutoGenerated(ForeignKeyConstraint fk, bool checkRelation)
	{
		return default(bool);
	}

	[Token(Token = "0x6000898")]
	[Address(RVA = "0x42BC8A0", Offset = "0x42BC8A0", VA = "0x42BC8A0")]
	private bool IsAutoGenerated(object o)
	{
		return default(bool);
	}

	[Token(Token = "0x6000899")]
	[Address(RVA = "0x42B7050", Offset = "0x42B7050", VA = "0x42B7050")]
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema, bool genNested)
	{
		return null;
	}

	[Token(Token = "0x600089A")]
	[Address(RVA = "0x42AF1E0", Offset = "0x42AF1E0", VA = "0x42AF1E0")]
	private void SetMSDataAttribute(XmlElement root, Type type)
	{
	}
}
