// ==================== AoTTG2 cross-reference ====================
// Type: System.Data.XmlTreeGen
// Update status: unchanged since the previous dump
// No native C: this type has no methods, or its assembly is out of native scope.
// Prior real C# source: none (type is newer than the last public source snapshot)
// Bodies below are empty IL2CPP metadata stubs; the logic lives in the native C.
// ===============================================================
using System.Collections;
using System.ComponentModel;
using System.Xml;
using Il2CppDummyDll;

namespace System.Data;

[Token(Token = "0x2000098")]
internal sealed class XmlTreeGen
{
	[Token(Token = "0x4000321")]
	[FieldOffset(Offset = "0x10")]
	private ArrayList _constraintNames;

	[Token(Token = "0x4000322")]
	[FieldOffset(Offset = "0x18")]
	private Hashtable _namespaces;

	[Token(Token = "0x4000323")]
	[FieldOffset(Offset = "0x20")]
	private Hashtable _autogenerated;

	[Token(Token = "0x4000324")]
	[FieldOffset(Offset = "0x28")]
	private Hashtable _prefixes;

	[Token(Token = "0x4000325")]
	[FieldOffset(Offset = "0x30")]
	private DataSet _ds;

	[Token(Token = "0x4000326")]
	[FieldOffset(Offset = "0x38")]
	private ArrayList _tables;

	[Token(Token = "0x4000327")]
	[FieldOffset(Offset = "0x40")]
	private ArrayList _relations;

	[Token(Token = "0x4000328")]
	[FieldOffset(Offset = "0x48")]
	private XmlDocument _dc;

	[Token(Token = "0x4000329")]
	[FieldOffset(Offset = "0x50")]
	private XmlElement _sRoot;

	[Token(Token = "0x400032A")]
	[FieldOffset(Offset = "0x58")]
	private int _prefixCount;

	[Token(Token = "0x400032B")]
	[FieldOffset(Offset = "0x5C")]
	private SchemaFormat _schFormat;

	[Token(Token = "0x400032C")]
	[FieldOffset(Offset = "0x60")]
	private string _filePath;

	[Token(Token = "0x400032D")]
	[FieldOffset(Offset = "0x68")]
	private string _fileName;

	[Token(Token = "0x400032E")]
	[FieldOffset(Offset = "0x70")]
	private string _fileExt;

	[Token(Token = "0x400032F")]
	[FieldOffset(Offset = "0x78")]
	private XmlElement _dsElement;

	[Token(Token = "0x4000330")]
	[FieldOffset(Offset = "0x80")]
	private XmlElement _constraintSeparator;

	[Token(Token = "0x4000331")]
	[FieldOffset(Offset = "0x88")]
	private Converter<Type, string> _targetConverter;

	[Token(Token = "0x600086A")]
	[Address(RVA = "0x45EA9C0", Offset = "0x45EA9C0", VA = "0x45EA9C0")]
	internal XmlTreeGen(SchemaFormat format)
	{
	}

	[Token(Token = "0x600086B")]
	[Address(RVA = "0x45EAA60", Offset = "0x45EAA60", VA = "0x45EAA60")]
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node)
	{
	}

	[Token(Token = "0x600086C")]
	[Address(RVA = "0x45EAA70", Offset = "0x45EAA70", VA = "0x45EAA70")]
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node, Type type)
	{
	}

	[Token(Token = "0x600086D")]
	[Address(RVA = "0x45EB210", Offset = "0x45EB210", VA = "0x45EB210")]
	internal void AddXdoProperties(object instance, XmlElement root, XmlDocument xd)
	{
	}

	[Token(Token = "0x600086E")]
	[Address(RVA = "0x45EB390", Offset = "0x45EB390", VA = "0x45EB390")]
	internal void AddXdoProperty(PropertyDescriptor pd, object instance, XmlElement root, XmlDocument xd)
	{
	}

	[Token(Token = "0x600086F")]
	[Address(RVA = "0x45EBD40", Offset = "0x45EBD40", VA = "0x45EBD40")]
	internal static string XmlDataTypeName(Type type)
	{
		return null;
	}

	[Token(Token = "0x6000870")]
	[Address(RVA = "0x45ECB30", Offset = "0x45ECB30", VA = "0x45ECB30")]
	private void GenerateConstraintNames(DataTable table, bool fromTable)
	{
	}

	[Token(Token = "0x6000871")]
	[Address(RVA = "0x45ED210", Offset = "0x45ED210", VA = "0x45ED210")]
	private void GenerateConstraintNames(ArrayList tables)
	{
	}

	[Token(Token = "0x6000872")]
	[Address(RVA = "0x45ED2F0", Offset = "0x45ED2F0", VA = "0x45ED2F0")]
	private void GenerateConstraintNames(DataSet ds)
	{
	}

	[Token(Token = "0x6000873")]
	[Address(RVA = "0x45ED640", Offset = "0x45ED640", VA = "0x45ED640")]
	private static bool _PropsNotEmpty(PropertyCollection props)
	{
		return default(bool);
	}

	[Token(Token = "0x6000874")]
	[Address(RVA = "0x45ED670", Offset = "0x45ED670", VA = "0x45ED670")]
	private bool HaveExtendedProperties(DataSet ds)
	{
		return default(bool);
	}

	[Token(Token = "0x6000875")]
	[Address(RVA = "0x45ED840", Offset = "0x45ED840", VA = "0x45ED840")]
	internal void WriteSchemaRoot(XmlDocument xd, XmlElement rootSchema, string targetNamespace)
	{
	}

	[Token(Token = "0x6000876")]
	[Address(RVA = "0x45EDA70", Offset = "0x45EDA70", VA = "0x45EDA70")]
	internal static void ValidateColumnMapping(Type columnType)
	{
	}

	[Token(Token = "0x6000877")]
	[Address(RVA = "0x45EDAE0", Offset = "0x45EDAE0", VA = "0x45EDAE0")]
	internal void SetupAutoGenerated(DataSet ds)
	{
	}

	[Token(Token = "0x6000878")]
	[Address(RVA = "0x45EEC30", Offset = "0x45EEC30", VA = "0x45EEC30")]
	internal void SetupAutoGenerated(ArrayList dt)
	{
	}

	[Token(Token = "0x6000879")]
	[Address(RVA = "0x45EDE30", Offset = "0x45EDE30", VA = "0x45EDE30")]
	internal void SetupAutoGenerated(DataTable dt)
	{
	}

	[Token(Token = "0x600087A")]
	[Address(RVA = "0x45EF470", Offset = "0x45EF470", VA = "0x45EF470")]
	private void CreateTablesHierarchy(DataTable dt)
	{
	}

	[Token(Token = "0x600087B")]
	[Address(RVA = "0x45EF8B0", Offset = "0x45EF8B0", VA = "0x45EF8B0")]
	private void CreateRelations(DataTable dt)
	{
	}

	[Token(Token = "0x600087C")]
	[Address(RVA = "0x45EFCD0", Offset = "0x45EFCD0", VA = "0x45EFCD0")]
	private DataTable[] CreateToplevelTables()
	{
		return null;
	}

	[Token(Token = "0x600087D")]
	[Address(RVA = "0x45F0030", Offset = "0x45F0030", VA = "0x45F0030")]
	internal void SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy)
	{
	}

	[Token(Token = "0x600087E")]
	[Address(RVA = "0x45F4270", Offset = "0x45F4270", VA = "0x45F4270")]
	internal XmlElement SchemaTree(XmlDocument xd, DataTable dt)
	{
		return null;
	}

	[Token(Token = "0x600087F")]
	[Address(RVA = "0x45F3470", Offset = "0x45F3470", VA = "0x45F3470")]
	internal XmlElement FillDataSetElement(XmlDocument xd, DataSet ds, DataTable dt)
	{
		return null;
	}

	[Token(Token = "0x6000880")]
	[Address(RVA = "0x45F75D0", Offset = "0x45F75D0", VA = "0x45F75D0")]
	internal void SetPath(XmlWriter xw)
	{
	}

	[Token(Token = "0x6000881")]
	[Address(RVA = "0x45F78C0", Offset = "0x45F78C0", VA = "0x45F78C0")]
	internal void Save(DataSet ds, XmlWriter xw)
	{
	}

	[Token(Token = "0x6000882")]
	[Address(RVA = "0x45F78F0", Offset = "0x45F78F0", VA = "0x45F78F0")]
	internal void Save(DataTable dt, XmlWriter xw)
	{
	}

	[Token(Token = "0x6000883")]
	[Address(RVA = "0x45F78E0", Offset = "0x45F78E0", VA = "0x45F78E0")]
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw)
	{
	}

	[Token(Token = "0x6000884")]
	[Address(RVA = "0x45F79A0", Offset = "0x45F79A0", VA = "0x45F79A0")]
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy)
	{
	}

	[Token(Token = "0x6000885")]
	[Address(RVA = "0x45F79B0", Offset = "0x45F79B0", VA = "0x45F79B0")]
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy, Converter<Type, string> multipleTargetConverter)
	{
	}

	[Token(Token = "0x6000886")]
	[Address(RVA = "0x45F3C70", Offset = "0x45F3C70", VA = "0x45F3C70")]
	internal XmlElement HandleRelation(DataRelation rel, XmlDocument dc)
	{
		return null;
	}

	[Token(Token = "0x6000887")]
	[Address(RVA = "0x45F7AF0", Offset = "0x45F7AF0", VA = "0x45F7AF0")]
	private static XmlElement FindSimpleType(XmlElement schema, string name)
	{
		return null;
	}

	[Token(Token = "0x6000888")]
	[Address(RVA = "0x45F7BF0", Offset = "0x45F7BF0", VA = "0x45F7BF0")]
	internal XmlElement GetSchema(string NamespaceURI)
	{
		return null;
	}

	[Token(Token = "0x6000889")]
	[Address(RVA = "0x45F7E60", Offset = "0x45F7E60", VA = "0x45F7E60")]
	internal void HandleColumnType(DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema)
	{
	}

	[Token(Token = "0x600088A")]
	[Address(RVA = "0x45F8370", Offset = "0x45F8370", VA = "0x45F8370")]
	internal void AddColumnProperties(DataColumn col, XmlElement root)
	{
	}

	[Token(Token = "0x600088B")]
	[Address(RVA = "0x45F89C0", Offset = "0x45F89C0", VA = "0x45F89C0")]
	private string FindTargetNamespace(DataTable table)
	{
		return null;
	}

	[Token(Token = "0x600088C")]
	[Address(RVA = "0x45F8AE0", Offset = "0x45F8AE0", VA = "0x45F8AE0")]
	internal XmlElement HandleColumn(DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal)
	{
		return null;
	}

	[Token(Token = "0x600088D")]
	[Address(RVA = "0x45F9890", Offset = "0x45F9890", VA = "0x45F9890")]
	internal static string TranslateAcceptRejectRule(AcceptRejectRule rule)
	{
		return null;
	}

	[Token(Token = "0x600088E")]
	[Address(RVA = "0x45F98E0", Offset = "0x45F98E0", VA = "0x45F98E0")]
	internal static string TranslateRule(Rule rule)
	{
		return null;
	}

	[Token(Token = "0x600088F")]
	[Address(RVA = "0x45F3BD0", Offset = "0x45F3BD0", VA = "0x45F3BD0")]
	internal void AppendChildWithoutRef(XmlElement node, string Namespace, XmlElement el, string refString)
	{
	}

	[Token(Token = "0x6000890")]
	[Address(RVA = "0x45F96C0", Offset = "0x45F96C0", VA = "0x45F96C0")]
	internal XmlElement FindTypeNode(XmlElement node, string strType)
	{
		return null;
	}

	[Token(Token = "0x6000891")]
	[Address(RVA = "0x45F3BC0", Offset = "0x45F3BC0", VA = "0x45F3BC0")]
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema)
	{
		return null;
	}

	[Token(Token = "0x6000892")]
	[Address(RVA = "0x45F9970", Offset = "0x45F9970", VA = "0x45F9970")]
	private bool HasMixedColumns(DataTable table)
	{
		return default(bool);
	}

	[Token(Token = "0x6000893")]
	[Address(RVA = "0x45EED10", Offset = "0x45EED10", VA = "0x45EED10")]
	internal static bool AutoGenerated(DataColumn col)
	{
		return default(bool);
	}

	[Token(Token = "0x6000894")]
	[Address(RVA = "0x45F9DC0", Offset = "0x45F9DC0", VA = "0x45F9DC0")]
	internal static bool AutoGenerated(DataRelation rel)
	{
		return default(bool);
	}

	[Token(Token = "0x6000895")]
	[Address(RVA = "0x45EF3B0", Offset = "0x45EF3B0", VA = "0x45EF3B0")]
	internal static bool AutoGenerated(UniqueConstraint unique)
	{
		return default(bool);
	}

	[Token(Token = "0x6000896")]
	[Address(RVA = "0x45EF3A0", Offset = "0x45EF3A0", VA = "0x45EF3A0")]
	private bool AutoGenerated(ForeignKeyConstraint fk)
	{
		return default(bool);
	}

	[Token(Token = "0x6000897")]
	[Address(RVA = "0x45F9EC0", Offset = "0x45F9EC0", VA = "0x45F9EC0")]
	internal static bool AutoGenerated(ForeignKeyConstraint fk, bool checkRelation)
	{
		return default(bool);
	}

	[Token(Token = "0x6000898")]
	[Address(RVA = "0x45FA000", Offset = "0x45FA000", VA = "0x45FA000")]
	private bool IsAutoGenerated(object o)
	{
		return default(bool);
	}

	[Token(Token = "0x6000899")]
	[Address(RVA = "0x45F47B0", Offset = "0x45F47B0", VA = "0x45F47B0")]
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema, bool genNested)
	{
		return null;
	}

	[Token(Token = "0x600089A")]
	[Address(RVA = "0x45EC940", Offset = "0x45EC940", VA = "0x45EC940")]
	private void SetMSDataAttribute(XmlElement root, Type type)
	{
	}
}
